image: python:3.13-slim-bookworm  # Default image

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN"

stages:
  - test
  - build
  - deploy

variables:
  PDM_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pdm"
  PIP_NO_CACHE_DIR: "off"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_PROGRESS_BAR: "off"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .cache/pdm
    - __pypackages__

test:
  stage: test
  before_script:
    - pip install pdm
    - pdm config cache_dir "$PDM_CACHE_DIR"
    - pdm sync --dev
  script:
    - pdm run pytest --cov=datacite_websnap --cov-report=term --no-cov-on-fail
  coverage: '/TOTAL.*\s+(\d+)%/'

test-tox:
  stage: test
  image: python:${PYTHON_VERSION}-slim-bookworm
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN"
    - pip install pdm
    - pdm sync --dev
  script:
    - pdm run tox -e py${PYTHON_VERSION}
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.11", "3.12", "3.13" ]
  when: manual

build:
  stage: build
  before_script:
    - pip install pdm
    - pdm config cache_dir "$PDM_CACHE_DIR"
    - pdm sync
  script:
    - pdm build
  artifacts:
    paths:
      - dist/*
  when: manual
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - when: manual

deploy:
  stage: deploy
  before_script:
    - pip install pdm
    - pdm sync
    - pdm config repository.gitlab.url "https://gitlabext.wsl.ch/api/v4/projects/$CI_PROJECT_NAME/packages/pypi/simple"
    - pdm config repository.gitlab.username "__token__"
    - pdm config repository.gitlab.password "$CI_DEPLOY_TOKEN"
  script:
    - pdm publish --repository gitlab
  environment:
    name: production
  dependencies:
    - build
  when: manual
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - when: manual
