image: python:3.13-slim-bookworm

stages:
  - test

test:
  stage: test
  variables:
    PDM_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pdm"
    PIP_NO_CACHE_DIR: "off"
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PIP_PROGRESS_BAR: "off"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .cache/pdm
      - __pypackages__
  before_script:
    - pip install pdm
    - pdm config cache_dir "$PDM_CACHE_DIR"
    - pdm sync --dev
  script:
    - pdm run pytest --cov=datacite_websnap --cov-report=term --no-cov-on-fail
  coverage: '/TOTAL.*\s+(\d+)%/'
