site_name: datacite-websnap
site_url: https://git-pages.wsl.ch/datacite-websnap-5b86d6
repo_url: https://git.wsl.ch/EnviDat/datacite-websnap

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Commands:
    - bulk-export: commands/bulk-export.md
    - doi-export: commands/doi-export.md
    - Common Options: commands/common-options.md
  - Usage:
    - S3 Bucket: usage/s3.md
    - Local Machine: usage/local.md
  - Reference:
    - Credentials: reference/credentials.md
    - DataCite API: reference/datacite-api.md
    - DataCite Filters: reference/filters.md
    - Metadata Record Naming: reference/record-naming.md
    - Logs: reference/logs.md
